Traceback (most recent call last):
  File "/home/nikos/dish/compiler/pash.py", line 97, in <module>
    main()
  File "/home/nikos/dish/compiler/pash.py", line 25, in main
    config.load_config(args.config_path)
  File "/home/nikos/dish/compiler/config.py", line 40, in load_config
    raise Exception('No valid configuration could be loaded from {}'.format(config_file_path))
Exception: No valid configuration could be loaded from /tmp/new-config.yaml

real	0m0.137s
user	0m0.129s
sys	0m0.008s
